Models/ErrorViewModel.cs
using System;

namespace MVCFormNotBinding.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Widget.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCFormNotBinding.Models
{
    public class Widget
    {
        /// <summary>
        /// Object name
        /// </summary>
        [Display(Name = "Product Name")]
        [Required(ErrorMessage ="A name is required.")]
        public String objName { get; set; }

        /// <summary>
        /// Object Description
        /// </summary>
        [Display(Name = "Product Description")]
        [Required(ErrorMessage = "A description is required.")]

        public String objDesc { get; set; }

        /// <summary>
        /// Object Unit Weight
        /// </summary>
        [Display(Name = "Product Unit Weight")]
        [Required(ErrorMessage = "A weight in decimal format is required.")]

        public Double objWeight { get; set; }

        /// <summary>
        /// Object Unit Cost to Purchase
        /// </summary>
        [Display(Name = "Product Unit Cost")]
        [Required(ErrorMessage = "A cost in $(USD) is required.")]

        public Double objUnitCost { get; set; }

        /// <summary>
        /// Object Customer Price for Sales
        /// </summary>
        [Display(Name = "Product Customer Price")]
        [Required(ErrorMessage = "A price in $(USD) is required.")]

        public Double objSalePrice { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCFormNotBinding.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCFormNotBinding.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WidgetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCFormNotBinding.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCFormNotBinding.Controllers
{
    public class WidgetController : Controller
    {
        [HttpGet]
        public IActionResult AddNoBind()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNoBind(IFormCollection form)
        {
            Widget product = new Widget()
            {
                objName = form["product-name"],
                objDesc = form["product-description"],
                objWeight = Convert.ToDouble(form["unit-weight"]),
                objUnitCost = Convert.ToDouble(form["unit-cost"]),
                objSalePrice = Convert.ToDouble(form["unit-price"])
            };

            //add code here to insert object into DB that isn't created

            //oh and make the DB

            ViewData["isAddedNoBind"] = $"{product.objName} has been created and added to the, oh wait nevermind.";

            return View();
        }

        [HttpGet]
        public IActionResult AddWithBind()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddWithBind(Widget product)
        {
            if (ModelState.IsValid)
            {
                ViewData["isAddedYesBind"] = $"{product.objName} has been created and added to the, oh wait nevermind.";
            }
            return View();
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCFormNotBinding</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCFormNotBinding</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Widget" asp-action="AddNoBind">Add a product (no-bind)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Widget" asp-action="AddWithBind">Add a product (yes-bind)</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCFormNotBinding - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Widget/AddNoBind.cshtml
@{
    ViewData["Title"] = "AddNoBind";
}

@if (ViewData["isAddedNoBind"] == null)
{
    <h1>AddNoBind</h1>

    <form method="post">
        <div class="form-group">
            <label for="objName">Product Name</label>
            <input type="text" name="product-name" class="form-control" id="objName">
            <small id="productNameHelp" class="form-text text-muted">Please enter the name of the product.</small>
        </div>
        <div class="form-group">
            <label for="objDesc">Product Description</label>
            <input type="text" name="product-description" class="form-control" id="objDesc">
            <small id="objdeschelp" class="form-text text-muted">Please enter a brief description of the product.</small>
        </div>
        <div class="form-group">
            <label for="objWeight">Product Weight</label>
            <input type="text" name="unit-weight" class="form-control" id="objWeight">
            <small id="objweighthelp" class="form-text text-muted">Please enter the full weight of the product.</small>
        </div>
        <div class="form-group">
            <label for="objUnitCost">Unit Purchase Cost</label>
            <input type="text" name="unit-cost" class="form-control" id="objUnitCost">
            <small id="unitcosthelp" class="form-text text-muted">Please enter the actual unit purchase cost.</small>
        </div>
        <div class="form-group">
            <label for="objSalePrice">Customer Sale Price</label>
            <input type="text" name="unit-price" class="form-control" id="objSalePrice">
            <small id="unitpricehelp" class="form-text text-muted">Please enter the unit customer sale price.</small>
        </div>
        <button type="submit" class="btn btn-primary">Add Product</button>
    </form>
}

else
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@ViewData["isAddedNoBind"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Widget/AddWithBind.cshtml
@model Widget
@{
    ViewData["Title"] = "AddWithBind";
}

<h1>AddWithBind</h1>

@if (ViewData["isAddedYesBind"] == null)
{
<form method="post">
    <div class="form-group">
        <label asp-for="objName"></label>
        <input asp-for="objName" class="form-control" />
        <small id="productNameHelp" class="form-text text-muted">Please enter the name of the product.</small>
        <span asp-validation-for="objName"></span>
    </div>
    <div class="form-group">
        <label asp-for="objDesc"></label>
        <input asp-for="objDesc" class="form-control" />
        <small id="objdeschelp" class="form-text text-muted">Please enter a brief description of the product.</small>
        <span asp-validation-for="objDesc"></span>
    </div>
    <div class="form-group">
        <label asp-for="objWeight"></label>
        <input asp-for="objWeight" class="form-control" />
        <small id="objweighthelp" class="form-text text-muted">Please enter the full weight of the product.</small>
        <span asp-validation-for="objWeight"></span>
    </div>
    <div class="form-group">
        <label asp-for="objUnitCost"></label>
        <input asp-for="objUnitCost" class="form-control" />
        <small id="unitcosthelp" class="form-text text-muted">Please enter the actual unit purchase cost.</small>
        <span asp-validation-for="objUnitCost"></span>
    </div>
    <div class="form-group">
        <label asp-for="objSalePrice"></label>
        <input asp-for="objSalePrice" class="form-control" />
        <small id="unitpricehelp" class="form-text text-muted">Please enter the unit customer sale price.</small>
        <span asp-validation-for="objSalePrice"></span>
    </div>
    <button type="submit" class="btn btn-primary">Add Product</button>

</form>
}
else
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@ViewData["isAddedYesBind"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}